---
language: node_js
node_js:
  - "6"

sudo: false
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-1.11
  - EMBER_TRY_SCENARIO=ember-1.12
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

after_success:
# Remove the downloaded copy of phantomJS
- rm -rf travis-phantomjs
# Add a remote, authenticating via an OAuth token (encrypted via "travis secure")
- git remote add deploy https://$GH_TOKEN:x-oauth-basic@github.com/mike-north/ember-perf.git 2>&1 >/dev/null
# Download all branches from this new remote (really the same remote, but different auth)
- git fetch deploy
# Check out a local copy of "master", but don't switch to it yet
- git branch gh-pages deploy/gh-pages
# Set up some required git config stuff (more env variables encrypted via "travis secure")
- git config user.name "Mike North"
- git config user.email "michael.l.north@gmail.com"
# Generate the github pages. When this command is finished I'll be on "master" branch with a
# new commit already made (but not pushed)
# Push the new commit
- /bin/bash lib/try-generate-pages.sh
